all:
	ghc solve.hs
small:
	./solve <  B-small-practice.in
large:
	./solve <  B-large-practice.in
send:	ssmall, slarge
	
ssmall:
	./solve <  B-small-practice.in >  B-small-practice.out
slarge:
	./solve <  B-large-practice.in >  B-large-practice.out
